name: Sync wLaunchELF Fork Weekly

on:
  schedule:
    - cron: "0 0 * * 0"  # Esegui ogni settimana a mezzanotte (UTC)
  repository_dispatch:
    types: [sync-wlaunchelf-fork]
  workflow_dispatch:  # Add this line to enable manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permesso per push

    steps:
      - name: Checkout del fork
        uses: actions/checkout@v4
        with:
          ref: master  # wLaunchELF usa "master" come branch principale

      - name: Aggiungi upstream remoto
        run: |
          git remote add upstream https://github.com/ps2homebrew/wLaunchELF.git
          git fetch upstream

      - name: Sincronizza con upstream
        run: |
          git checkout master
          git merge upstream/master
          git push origin master
